_target_: projects.ncap.src.quadruped.models.monolithic_ff_es
actor_hidden_sizes: [256]
actor_hidden_init:
  _target_: projects.ncap.src.evolution.init_linear_zeros_
  _partial_: true
actor_head_init:
  _target_: projects.ncap.src.evolution.init_linear_zeros_
  _partial_: true
