# @package _global_
# Train monolithic architecture with ES algorithm.
name: quadruped/1_mlp_tests/1_monolithic_es

hydra:
  sweeper:
    params:
      quadruped/robot/obs@robot: legs_feet
      quadruped/arena@arena: floor
      quadruped/model/es@model: monolithic_ff_mlpD_zeroall, monolithic_ff_mlpDxD_zeroall
      actor_hidden_size: 4, 8, 16, 32, 64, 128
      target_vx: 0.5
      seed: range(1, 11)

actor_hidden_size: 256

compute:
  # arena=floor
  mem: 16
  time: ${prod:60,7}

defaults:
  - /quadruped/1_mlp_tests/0_base_es
  - /quadruped/robot/obs@robot: legs_feet
  - /quadruped/model/es@model: monolithic_ff_mlpDxD_zeroall
  - _self_
