name: ncap
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - numpy>=1.24
  - cudatoolkit=11.6
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchvision=0.13
  - torchaudio=0.13
  - pandas>=1.5
  - jupyterlab>=4.1
  - ipywidgets>=8.0
  - mediapy=1.1.8
  - matplotlib>=3.7
  - seaborn>=0.12
  - scipy>=1.10
  - scikit-learn>=1.2
  - scikit-image>=0.19
  - imageio>=2.19
  - imageio-ffmpeg>=0.4
  - pillow>=9.3
  - pyyaml>=6.0
  - termcolor>=2.1
  - tqdm>=4.64
  - pre-commit>=3.0
  - pip:
      - mujoco==2.3.2
      - dm-control==1.0.10
      - gym==0.21.0
      - hydra-core==1.3.1
      - hydra-submitit-launcher==1.2.0
      - click==8.1.3
      - ray==2.5.1
      - orjson==3.9.2
      - dill==0.3.6
      - hsluv==5.0.3
      - ffmpeg-python==0.2.0
      - pyfluidsynth==1.3.3
